BOARD="orangepi4pro"
BRANCH="current"
RELEASE="bookworm"
BUILD_MINIMAL="yes"
BUILD_DESKTOP="no"
BUILD_OPT="image"
KERNEL_CONFIGURE="no"
CLEAN_LEVEL="make,debs,oldcache"
CREATE_PATCHES="no"
DEST_LANG="en_US.UTF-8"
EXTERNAL_NEW="prebuilt"
LIB_TAG="master"
USE_TORRENT="yes"
COMPRESS_OUTPUTIMAGE="no"
NO_APT_CACHER="yes"
PACKAGE_LIST="devmem2 i2c-tools usbutils strace"
PACKAGE_LIST_BOARD_REMOVE="figlet toilet mc nano smartmontools cracklib-runtime libcrack2 iozone3 dialog network-manager-openvpn wireless-tools resolvconf dconf-cli console-setup whiptail lm-sensors lsof sysstat"
ENABLE_EXTENSIONS="ffs_app"
